// <auto-generated />
using System;
using Altinn.AccessMgmt.PersistenceEF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Altinn.AccessMgmt.PersistenceEF.Migrations.AuditDb
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Urn")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("area", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditAreaGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Urn")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("areagroup", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("assignment", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditAssignmentPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("AssignmentPackage", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditAssignmentResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("AssignmentResource", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditDelegation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("FacilitatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("Delegation", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditDelegationPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<Guid>("DelegationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("DelegationPackage", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditDelegationResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<Guid>("DelegationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("DelegationResource", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefId")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("Entity", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditEntityLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("EntityLookup", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditEntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("EntityType", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditEntityVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("EntityVariant", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditEntityVariantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("EntityVariantRole", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasResources")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAssignable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelegable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Urn")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("package", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditPackageResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("PackageResource", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RefId")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("Provider", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditProviderType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("ProviderType", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefId")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("Resource", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("ResourceType", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAssignable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKeyRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Urn")
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("Role", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditRoleLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("RoleLookup", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditRoleMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("GetRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HasRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("RoleMap", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditRolePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<bool>("CanAssign")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelegate")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid?>("EntityVariantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasAccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("RolePackage", "history");
                });

            modelBuilder.Entity("Altinn.AccessMgmt.PersistenceEF.Models.AuditRoleResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_changeoperation");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedby");

                    b.Property<Guid?>("ChangedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_changedbysystem");

                    b.Property<string>("DeleteOperation")
                        .HasColumnType("text")
                        .HasColumnName("audit_deleteoperation");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedby");

                    b.Property<Guid?>("DeletedBySystem")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_deletedbysystem");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audit_validto");

                    b.HasKey("Id", "ChangeOperation");

                    b.ToTable("RoleResource", "history");
                });
#pragma warning restore 612, 618
        }
    }
}
