GRANT USAGE ON SCHEMA consent TO platform_authorization;
GRANT SELECT,INSERT,UPDATE,REFERENCES,DELETE,TRUNCATE,TRIGGER ON ALL TABLES IN SCHEMA consent TO platform_authorization;
GRANT ALL ON ALL SEQUENCES IN SCHEMA consent TO platform_authorization;
