// <autogenerated />
namespace Altinn.Authorization.Importers.ResReg.Models;

/// <summary>
/// LanguageText
/// </summary>
public class LanguageText
{
    /// <summary>
    /// English
    /// </summary>
    public string En { get; set; }

    /// <summary>
    /// Bokmål
    /// </summary>
    public string Nb { get; set; }

    /// <summary>
    /// Nynorsk
    /// </summary>
    public string Nn { get; set; }

    /// <summary>
    /// Returns first available
    /// Nb ?? En ?? Nn ?? ""
    /// </summary>
    /// <returns></returns>
    public override string ToString()
    {
        return Nb ?? En ?? Nn ?? "";
    }

}




/// <summary>
/// ResourceReference
/// </summary>
public class ResourceReference
{
    /// <summary>
    /// ReferenceSource
    /// </summary>
    public string ReferenceSource { get; set; }

    /// <summary>
    /// Reference
    /// </summary>
    public string Reference { get; set; }

    /// <summary>
    /// ReferenceType
    /// </summary>
    public string ReferenceType { get; set; }
}

/// <summary>
/// HasCompetentAuthority
/// </summary>
public class HasCompetentAuthority
{
    /// <summary>
    /// Name
    /// </summary>
    public LanguageText Name { get; set; }

    /// <summary>
    /// Organization
    /// </summary>
    public string Organization { get; set; }

    /// <summary>
    /// Orgcode
    /// </summary>
    public string Orgcode { get; set; }
}

/// <summary>
/// AuthorizationReference
/// </summary>
public class AuthorizationReference
{
    /// <summary>
    /// Id
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    /// Value
    /// </summary>
    public string Value { get; set; }
}

/// <summary>
/// RawResource
/// </summary>
public class RawResource
{
    /// <summary>
    /// Identifier
    /// </summary>
    public string Identifier { get; set; }

    /// <summary>
    /// Title
    /// </summary>
    public LanguageText Title { get; set; }

    /// <summary>
    /// Description
    /// </summary>
    public LanguageText Description { get; set; }

    /// <summary>
    /// RightDescription
    /// </summary>
    public LanguageText RightDescription { get; set; }

    /// <summary>
    /// Homepage
    /// </summary>
    public string Homepage { get; set; }

    /// <summary>
    /// Status
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// IsPartOf
    /// </summary>
    public string IsPartOf { get; set; }

    /// <summary>
    /// ResourceReferences
    /// </summary>
    public List<ResourceReference> ResourceReferences { get; set; }

    /// <summary>
    /// Delegable
    /// </summary>
    public bool Delegable { get; set; }

    /// <summary>
    /// Visible
    /// </summary>
    public bool Visible { get; set; }

    /// <summary>
    /// HasCompetentAuthority
    /// </summary>
    public HasCompetentAuthority HasCompetentAuthority { get; set; }

    /// <summary>
    /// AccessListMode
    /// </summary>
    public string AccessListMode { get; set; }

    /// <summary>
    /// SelfIdentifiedUserEnabled
    /// </summary>
    public bool SelfIdentifiedUserEnabled { get; set; }

    /// <summary>
    /// EnterpriseUserEnabled
    /// </summary>
    public bool EnterpriseUserEnabled { get; set; }

    /// <summary>
    /// ResourceType
    /// </summary>
    public string ResourceType { get; set; }

    /// <summary>
    /// AuthorizationReference
    /// </summary>
    public List<AuthorizationReference> AuthorizationReference { get; set; }
}
