using Altinn.Authorization.AccessPackages.Models;

namespace AccessPackages.MetaWeb.Repo
{
    public class Meta
    {
        public Guid Id { get; set; }
        public Guid RefId { get; set; }
        public string Title { get; set; }
        public string Ingress { get; set; }
        public string Body { get; set; }

    }


    public class LocalRepo
    {

        public List<AreaGroup> Groups { get; set; }

        public List<Area> Areas { get; set; }

        public List<Package> Packages { get; set; }

        public LocalRepo()
        {
            Load();
        }

        private void Load()
        {
            Packages = new List<Package>();

            Groups = new List<AreaGroup>()
            {
                new AreaGroup() { Id = Guid.Parse("7e2a3af8-08cb-43a9-bdd7-7d5c7e377145"), Name = "Vanlig", Description = "Mest vanlige pakkenegruppene" },
                new AreaGroup() { Id = Guid.Parse("3757643a-316d-4d0e-a52b-4dc7cdebc0b4"), Name = "Bransje", Description = "For bransje pakkergrupper" },
                new AreaGroup() { Id = Guid.Parse("554f0321-53b8-4d97-be12-6a585c507159"), Name = "Spesiell", Description = "For de spesielle pakkegruppene" },
            };

            Areas = new List<Area>()
            {
                new Area() { Id = Guid.Parse("7d32591d-34b7-4afc-8afa-013722f8c05d"), Name = "Skatt, avgift, regnskap og toll", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til skatt, avgift, regnskap og toll.", GroupId = Groups.First(t => t.Name == "Vanlig").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("6f7f3b02-8b5a-4823-9468-0f4646d3a790"), Name = "Personale", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til personale.", GroupId = Groups.First(t => t.Name == "Vanlig").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("a8834a7c-ed89-4c73-b5d5-19a2347f3b13"), Name = "Miljø, ulykke og sikkerhet", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til miljø, ulykke og sikkerhet.", GroupId = Groups.First(t => t.Name == "Vanlig").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("6f938de8-34f2-4bab-a0c6-3a3eb64aad3b"), Name = "Post og arkiv", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til post og arkiv.", GroupId = Groups.First(t => t.Name == "Vanlig").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("3f5df819-7aca-49e1-bf6f-3e8f120f20d1"), Name = "Forhold ved virksomheten", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til forhold ved virksomheten.", GroupId = Groups.First(t => t.Name == "Vanlig").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("892e98c6-1696-46e7-9bb1-59c08761ec64"), Name = "Integrasjoner", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til integrasjoner.", GroupId = Groups.First(t => t.Name == "Vanlig").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("e4ae823f-41db-46ed-873f-8a5d1378fff8"), Name = "Administrere tilganger", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til administrere tilganger.", GroupId = Groups.First(t => t.Name == "Vanlig").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("fc93d25e-80bc-469a-aa43-a6cee80eb3e2"), Name = "Jordbruk, skogbruk, jakt, fiske og akvakultur", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til jordbruk, skogbruk, jakt, fiske og akvakultur.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("536b317c-ef85-45d4-9b48-6511578e1952"), Name = "Bygg, anlegg og eiendom", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til bygg, anlegg og eiendom.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("6ff90072-566b-4acd-baac-ec477534e712"), Name = "Transport og lagring", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til transport og lagring.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("eab59b26-833f-40ca-9e27-72107e8f1908"), Name = "Helse, pleie, omsorg og vern", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til helse, pleie, omsorg og vern.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("7326614F-CF7C-492E-8E7F-D74E6E4A8970"), Name = "Oppvekst og utdaning", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til oppvekst og utdaning.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("6e152c10-0f63-4060-9b14-66808e7ac320"), Name = "Energi, vann,avløp og avfall", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til energi, vann,avløp og avfall.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("10c2dd29-5ab3-4a26-900e-8e2326150353"), Name = "Industrier", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til industrier.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("5996ba37-6db0-4391-8918-b1b0bd4b394b"), Name = "Kultur og frivillighet", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til kultur og frivillighet.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("3797e9f0-dd83-404c-9897-e356c32ef600"), Name = "Handel, overnatting og servering", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til handel, overnatting og servering.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("e31169f6-d4c7-4e45-93c7-f90bc285b639"), Name = "Andre tjenesteytende næringer", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til andre tjenesteytende næringer.", GroupId = Groups.First(t => t.Name == "Bransje").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("64CBCDC8-01C9-448C-B3D2-EB9582BEB3C2"), Name = "Fullmakter for regnskapsfører", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til fullmakter for regnskapsfører.", GroupId = Groups.First(t => t.Name == "Spesiell").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("7DF15290-F43C-4831-A1B4-3EDFA43E526D"), Name = "Fullmakter for revisor", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til fullmakter for revisor.", GroupId = Groups.First(t => t.Name == "Spesiell").Id, IconName = "default" },
                new Area() { Id = Guid.Parse("F3DADDB7-6E21-455E-B6D2-65A281375B6B"), Name = "Fullmakter for konkursbo", Description = "Dette fullmaktsområdet omfatter tilgangspakker knyttet til fullmakter for konkursbo.", GroupId = Groups.First(t => t.Name == "Spesiell").Id, IconName = "default" },
            };

            var digdirProvider = new Provider() { Id = Guid.Parse("79c8bf42-5f6e-4e05-859b-15a16a4919a6"), Name = "Digdir", RefId = "991825827" };
            var brregProvider = new Provider() { Id = Guid.Parse("323f9ff9-11ad-4af3-8ccb-0db7bdb71d75"), Name = "Brønnøysundregistrene", RefId = "0" };
            var entityType = new EntityType() { Id = Guid.Parse("8c216e2f-afdd-4234-9ba2-691c727bb33d"), Name = "Organisasjon", ProviderId = brregProvider.Id };

            Packages = new List<Package>()
            {
                new Package() { Id = Guid.Parse("955D5779-3E2B-4098-B11D-0431DC41DDBE"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Regnskapsfører med signeringsrettighet", Description = "Denne fullmakten gir tilgang til regnskapfører å kunne signere på vegne av kunden for alle tjenester som krever signeringsrett. Dette er tjenester som man har vurdert det som naturlig at en regnskapsfører utfører på vegne av sin kunde. Fullmakten gis kun til autoriserte regnskapsførere. Fullmakt hos regnskapfører oppstår når kunden registrerer regnskapsfører i Enhetsregisteret. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Fullmakter for regnskapsfører").Id, HasResources = false },
                new Package() { Id = Guid.Parse("A5F7F72A-9B89-445D-85BB-06F678A3D4D1"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Regnskapsfører uten signeringsrettighet", Description = "Denne fullmakten gir tilgang til å kunne utføre alle tjenester som ikke krever signeringsrett. Dette er tjenester som man har vurdert det som naturlig at en regnskapsfører utfører på vegne av sin kunde. Fullmakten gis kun til autoriserte regnskapsførere. Fullmakt hos regnskapfører oppstår når kunden registrerer regnskapsfører i Enhetsregisteret. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Fullmakter for regnskapsfører").Id, HasResources = false },
                new Package() { Id = Guid.Parse("43BECC6A-8C6C-4E9E-BB2F-08FE588ADA21"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Regnskapsfører lønn", Description = "Denne fullmakten gir tilgang til regnskapsfører å rapportere lønn for sin kunde. Dette er tjenester som man har vurdert det som naturlig at en regnskapsfører utfører på vegne av sin kunde. Fullmakten gis kun til autoriserte regnskapsførere. Fullmakt hos regnskapfører oppstår når kunden registrerer regnskapsfører i Enhetsregisteret. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Fullmakter for regnskapsfører").Id, HasResources = false },
                new Package() { Id = Guid.Parse("2F176732-B1E9-449B-9918-090D1FA986F6"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Ansvarlig revisor", Description = "Denne fullmakten gir revisor tilgang til å opptre som ansvarlig revisor for en kunde og utføre alle tjenester som krever denne fullmakten. Dette er tjenester som tjenestetilbyder har vurdert det som naturlig at en revisor utfører på vegne av sin kunde. Fullmakten gis kun til autoriserte revisorer. Fullmakt hos revisor oppstår når kunden registrerer regnskapsfører i Enhetsregisteret. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Fullmakter for revisor").Id, HasResources = false },
                new Package() { Id = Guid.Parse("96120C32-389D-46EB-8212-0A6540540C25"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Revisormedarbeider", Description = "Denne fullmakten gir revisor tilgang til å opptre som revisormedarbeider for en kunde og utføre alle tjenester som krever denne fullmakten. Dette er tjenester som tjenestetilbyder har vurdert det som naturlig at en revisor utfører på vegne av sin kunde. Fullmakten gis kun til autoriserte revisorer. Fullmakt hos revisor oppstår når kunden registrerer regnskapsfører i Enhetsregisteret. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Fullmakter for revisor").Id, HasResources = false },
                new Package() { Id = Guid.Parse("A6D704B7-D56B-4517-BE79-0ACD5B55B35E"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Varehandel", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til varehandel, inkludert engros- og detaljhandel, import og eksport, og salg og reparasjon av motorvogner. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Handel, overnatting og servering").Id, HasResources = true },
                new Package() { Id = Guid.Parse("77CDD23A-DDDF-43E6-B5C2-0D8299B0888C"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Overnatting", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til overnattingsvirksomhet. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Handel, overnatting og servering").Id, HasResources = true },
                new Package() { Id = Guid.Parse("6710A7A0-78F9-47E3-BFA6-0D875869BEFD"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Servering", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til serveringsvirksomhet. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Handel, overnatting og servering").Id, HasResources = true },
                new Package() { Id = Guid.Parse("03404270-AA2D-498F-9E6A-103043D41F1F"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Kommuneoverlege", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til sykehus, lege, tannlege og hjemmesykepleie,fysioterapi, ambulanse og lignende, som er relevant for kommuneleger. Denne fullmakten kan gi bruker tilgang til personopplysninger om personer det rapporteres om. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Helse, pleie, omsorg og vern").Id, HasResources = true },
                new Package() { Id = Guid.Parse("5A642040-46CF-4466-B671-115A022E3048"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Helsetjenester med personopplysninger av særlig kategori", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til sykehus, lege, tannlege og hjemmesykepleie,fysioterapi, ambulanse og lignende, som er av særlig kategori. Denne fullmakten kan gi bruker tilgang til sensitive personopplysninger om personer det rapporteres om. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Helse, pleie, omsorg og vern").Id, HasResources = true },
                new Package() { Id = Guid.Parse("4FA0FBBC-3841-4405-9D94-12731A8FDB81"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Helsetjenester", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til sykehus, lege, tannlege og hjemmesykepleie,fysioterapi, ambulanse og lignende. Denne fullmakten kan gi bruker tilgang til personopplysninger om personer det rapporteres om. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Helse, pleie, omsorg og vern").Id, HasResources = true },
                new Package() { Id = Guid.Parse("4D71E7B8-C6EB-4E33-9A64-1279A509A53B"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Pleie og omsorgstjeneter i institusjon", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til pleie og omsorgstilbud i institursjon. Dette er tjenester som tilbyr institusjonsopphold kombinert med sykepleie, tilsyn eller annen form for pleie alt etter hva som kreves av beboerne. Denne fullmakten kan gi bruker tilgang til helseopplysninger om personer det rapporteres om. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Helse, pleie, omsorg og vern").Id, HasResources = true },
                new Package() { Id = Guid.Parse("70831546-6BFA-45A0-BDAD-14E9DB265847"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Sosiale omsorgstjenester uten botilbud og flyktningemottak", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til sosiale omsorgstjeneser uten botilbud for eldre, funksjonshemmede og rusmisbrukere samt flykningemottak, og tjenester relatert til arbeidstrening og andre sosiale tjenester, f eks i regi av velferdsorganisasjoner. Denne fullmakten kan gi bruker tilgang til helseopplysninger om personer det rapporteres om. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Helse, pleie, omsorg og vern").Id, HasResources = true },
                new Package() { Id = Guid.Parse("98C404F4-5350-42CD-86D0-15FD38F178C4"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Familievern", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til familievern. Denne fullmakten kan gi bruker tilgang til helseopplysninger om personer det rapporteres om. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir. OBS! Vær oppmerksom på at tilgangspakken inneholder fullmakter som kan ha sensitiv karakter. Vurder om fullmaktene skal gis som enkeltrettigheter.", AreaId = Areas.First(t => t.Name == "Helse, pleie, omsorg og vern").Id, HasResources = true },
                new Package() { Id = Guid.Parse("83FF0734-0DE5-4C2A-939B-18A9452C00BC"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Barnevern", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til barnevern. Denne fullmakten kan gi bruker tilgang til helseopplysninger om personer det rapporteres om. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir. OBS! Vær oppmerksom på at tilgangspakken inneholder fullmakter som kan ha sensitiv karakter. Vurder om fullmaktene skal gis som enkeltrettigheter.", AreaId = Areas.First(t => t.Name == "Helse, pleie, omsorg og vern").Id, HasResources = true },
                new Package() { Id = Guid.Parse("65C7BBE7-AEB4-4F18-B0B0-1B1B83BD24D1"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Næringsmidler, drikkevarer og tobakk", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med næringsmidler, drikkevarer og tobakk. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("C6231D60-5373-4179-B98B-1E7EB83DA474"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Tekstiler, klær og lærvarer", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med tekstiler, klær og lærvarer. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("DEB1618F-395C-4A14-9A70-20E90E5F9A76"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Trelast, trevarer og papirvarer", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med trelast, trevarer og papirvarer. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("965F9ACA-48F5-4A16-B5E3-228806AD4FA7"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Trykkerier og reproduksjon av innspilte opptak", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med trykkerier og reproduksjon av innspilte opptak. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("79203DF9-D71B-460B-A828-22B0BF79F335"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Oljeraffinering, kjemisk og farmasøytisk industri", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med oljeraffinering, kjemisk og farmasøytisk industri. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("573BE5D2-3DDD-4862-9711-2350147A1B25"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Gummi, plast og ikke-metallholdige mineralprodukter", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med gummi, plast og ikke-metallholdige mineralprodukter. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("84E744A0-E93F-4CAF-BB3F-24387F045D2D"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Metaller og mineraler", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med metaller og mineraler. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("2857FD90-DAD2-4CC3-9947-282C22F5D2DC"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Metallvarer elektrisk utstyr og maskiner", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med metallvarer, elektrisk utstyr og maskiner. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("C37AABDF-A78A-4F59-999A-298A83E9E113"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Verft og andre transportmidler", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med verft og andre transportmidler. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("07BFD8A5-5B13-4937-84B9-2BD6AC726EA1"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Møbler og annen industri", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med møbler og annen industri. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("EC492675-3A48-4AD9-B864-2D6865020642"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Reparasjon og installasjon av maskiner og utstyr", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med reparasjon og installasjon av maskiner og utstyr. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("8C700369-8FFF-40F1-B4CE-2F116416D804"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Bergverk", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til industri i forbindelse med bergverk og tilhørende tjenester til bergverksdrift og utvinning. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Industrier").Id, HasResources = true },
                new Package() { Id = Guid.Parse("37D2BA7F-187F-45F5-9A96-2F23CF328DAB"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Programmeringsgrensesnitt (API)", Description = "Denne tilgangspakken gir fullmakter til å administrere tilgang til data og programmeringsgrensenitt (API) som benytter Maskinporten eller tilsvarende løsninger for APIsikring. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Integrasjoner").Id, HasResources = true },
                new Package() { Id = Guid.Parse("04B3A462-43F6-4435-9D12-2F42DF6B45FC"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Opptre for virksomhetens kunder", Description = "NaN", AreaId = Areas.First(t => t.Name == "Integrasjoner").Id, HasResources = true },
                new Package() { Id = Guid.Parse("66BD8101-FBD8-491B-B1F5-2F53A9476FFD"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Maskinlesbare hendelser", Description = "Denne tilgangspakken gir fullmakter til å administrere tilgang til maskinlesbare hendelser. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Integrasjoner").Id, HasResources = true },
                new Package() { Id = Guid.Parse("44746BAD-AAE5-4A83-B2E1-30A7CC9B809D"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Programmeringsgrensesnitt NUF (API)", Description = "Denne tilgangspakken gir fullmakter til å administrere tilgang til data og programmeringsgrensenitt (API) som benytter Maskinporten eller tilsvarende løsninger for APIsikring på vegne av norskregistrerte utenlandske foretak (NUF). Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Integrasjoner").Id, HasResources = true },
                new Package() { Id = Guid.Parse("C5BBBC3F-605A-4DCB-A587-32124D7BB76D"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Jordbruk", Description = "Denne tilgangspakken gir tilgang til tjenester knyttet til jordbruk. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Jordbruk, skogbruk, jakt, fiske og akvakultur").Id, HasResources = true },
                new Package() { Id = Guid.Parse("7B8A3AAA-C8ED-4AC4-923A-335F4F9EB45A"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Dyrehold", Description = "Denne tilgangspakken gir tilgang til tjenester knyttet til dyrehold. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Jordbruk, skogbruk, jakt, fiske og akvakultur").Id, HasResources = true },
                new Package() { Id = Guid.Parse("0BB5963E-DF17-4F35-B913-3CE10A34B866"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Reindrift", Description = "Denne tilgangspakken gir tilgang til tjenester knyttet til reindrift. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Jordbruk, skogbruk, jakt, fiske og akvakultur").Id, HasResources = true },
                new Package() { Id = Guid.Parse("906AEC0D-AD1F-496B-A0BB-40F81B3303CB"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Jakt og viltstell", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til jakt og viltstell. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Jordbruk, skogbruk, jakt, fiske og akvakultur").Id, HasResources = true },
                new Package() { Id = Guid.Parse("F7E02568-90B6-477D-8ABB-44984DDEB1F9"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Skogbruk", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til skogbruk. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Jordbruk, skogbruk, jakt, fiske og akvakultur").Id, HasResources = true },
                new Package() { Id = Guid.Parse("9D2EC6E9-5148-4F47-9AE4-4536F6C9C1CB"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Fiske", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til fiske. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Jordbruk, skogbruk, jakt, fiske og akvakultur").Id, HasResources = true },
                new Package() { Id = Guid.Parse("78C21107-7D2D-4E85-AF82-47EA0E47CECA"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Akvakultur", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til akvakultur og fiskeoppdrett. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Jordbruk, skogbruk, jakt, fiske og akvakultur").Id, HasResources = true },
                new Package() { Id = Guid.Parse("75FA5863-3368-4AC6-9A4B-48F595E483AD"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Kunst og underholdning", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til kunstnerisk og underholdningsaktiviteter. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Kultur og frivillighet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("73418C0C-D4DB-4E26-8581-4CCF1384AAD7"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Biblioteker, museer, arkiver og annen kultur", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til biblioteker, museer, arkiver, og annen kultur som botaniske og zoologiske hager, og drift av naturfenomener av historisk, kulturell eller undervisningsmessig interesse (f.eks. verdenskulturarv mv.). Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Kultur og frivillighet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("CC5CCDEC-6C67-4462-AB51-4D5EAAFD64C1"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Lotteri og spill", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til lotteri og spill, som f eks kasinoer, bingohaller og videospillhaller samt spillevirksomhet som f.eks. lotterier og veddemål som inngås utenfor banen. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Kultur og frivillighet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("D2D00311-CC33-47AD-B33B-4EB15CCE8D1D"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Sport og fritid", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til sports- og fritidsaktiviteter. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Kultur og frivillighet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("C82AB275-DAD6-461A-BF0C-50BE46B25EC9"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Fornøyelser", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til drift av fornøyelsesetablissementer. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Kultur og frivillighet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("F05153B5-4784-46F0-805A-525ED31FDE3B"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Politikk", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til aktiviteter i forbindelse med politisk arbeid. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Kultur og frivillighet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("5EB07BDC-5C3C-4C85-ADD3-5405B214B8A3"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Renovasjon", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til renovasjon. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Miljø, ulykke og sikkerhet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("04C5A001-5249-4765-AE8E-58617C404223"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Miljørydding, miljørensing og lignende", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til miljørydding, miljørensing og lignende. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Miljø, ulykke og sikkerhet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("BACC9294-56FD-457F-930E-59EE4A7A3894"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Bærekraft", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til tiltak og rapportering på bærekraft. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Miljø, ulykke og sikkerhet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("CFE074FA-0A66-4A4B-974A-5D1DB8EB94E6"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Sikkerhet og internkontroll", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til sikkerhet og internkontroll. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Miljø, ulykke og sikkerhet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("A03AF7D5-74B9-4F18-AEAD-5D47EDC36BE5"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Ulykke", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til ulykke. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Miljø, ulykke og sikkerhet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("FA84BFFC-AC17-40CD-AF9C-61C89F92E44C"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Yrkesskade", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til yrkesskade. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Miljø, ulykke og sikkerhet").Id, HasResources = true },
                new Package() { Id = Guid.Parse("8CF4EC08-90DC-47D0-93F8-64A50C9B38B0"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Godkjenning av personell", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til å søke om godkjenning til enkeltpersoner. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("B56D2614-3F9D-4D93-8A8E-64D80B654AD7"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Godkjenning av utdanningsvirksomhet", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til å søke om godkjenning av utdanningsvirksomheter. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("93F37A3D-F799-47B3-BC8E-675B5813ABF4"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Høyere utdanning og høyere yrkesfaglig utdanning", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til høyere utdanning og høyere yrkesfaglig utdanning. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("219EA5F7-EB30-424F-A958-67D3C7E7A4C2"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "SFO-leder", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til førskole og fritidsordning. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("4CD69693-AFF0-4E88-8B64-6B5620672468"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "PPT-leder", Description = "Denne fullmakten gir tilgang til tjenester innen drift av Pedagogisk-psykologisk tjeneste (PPT) som PPT-leder er ansvarlig for. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("40397A93-B047-4011-A6B8-6B8AF16B6324"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Opplæringskontorleder", Description = "Denne fullmakten gir tilgang til tjenester innen drift av opplæringskontor som opplæringskontorleder er ansvarlig for. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("499D0E1C-18D7-4F21-B110-723E3D13003A"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Skoleleder", Description = "Denne fullmakten gir tilgang til tjenester innen drift av skole som skoleleder er ansvarlig for. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("32BFD131-1570-4B0C-888B-733CBB72D0CB"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Skoleeier", Description = "Denne fullmakten gir tilgang til tjenester innen drift av skole som skoleeier er ansvarlig for. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("C1242DF4-6AF1-4E0B-B022-73C1099F5297"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Statsforvalter - skole og opplæring", Description = "Denne fullmakten gir tilgang til tjenester for statsforvalter knyttet til skole- og opplæringssektor, herunder fagopplæring og voksenopplæring.", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("7E6D8DD4-35A3-49D6-A2C5-73CD35018646"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Statsforvalter- barnehage", Description = "Denne fullmakten gir tilgang til tjenester for statsforvalter knyttet til barnehagesektor.", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("0ECC481A-691C-496D-A3F2-748B8C450ED9"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Barnehagemyndighet", Description = "Denne fullmakten gir tilgang til tjenester innen drift av barnehage som barnehagemyndighet er ansvarlig for. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("DCB57F3E-0E5B-4EF7-A10C-74C53BC5A90D"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Barnehageleder", Description = "Denne fullmakten gir tilgang til tjenester innen drift av barnehage som barnehageleder er ansvarlig for. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("9A14F2C1-F0BC-4965-97C0-76A4E191BBE1"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Barnehageeier", Description = "Denne fullmakten gir tilgang til tjenester innen drift av barnehage som barnehageeier er ansvarlig for. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Oppvekst og utdaning").Id, HasResources = true },
                new Package() { Id = Guid.Parse("CF575D42-72BE-4D14-B0D2-77352221DF4F"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Ansettelsesforhold", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til ansettelsesforhold. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Personale").Id, HasResources = true },
                new Package() { Id = Guid.Parse("FB0AA257-E7DC-4B7B-9528-77DFB749461C"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Lønn", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til lønn og honorar. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Personale").Id, HasResources = true },
                new Package() { Id = Guid.Parse("4AF2D44D-F9F8-4585-B679-7875BB1828EA"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "A-ordningen", Description = "Denne tilgangspakken gir fullmakter til tjenester som inngår i A-ordningen. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  OBS! Vær oppmerksompå at tilgangspakken inneholder fullmakter som kan ha sensitiv karakter. Vurder om fullmaktene skal gis som enkeltrettigheter.", AreaId = Areas.First(t => t.Name == "Personale").Id, HasResources = true },
                new Package() { Id = Guid.Parse("AE41BF08-C7EF-4BFE-B2B9-7BF6DEB7798F"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Pensjon", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til pensjon. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Personale").Id, HasResources = true },
                new Package() { Id = Guid.Parse("08EC673D-9126-4ED0-AE75-7CEEC8633C77"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Sykefravær", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til sykefravær. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Personale").Id, HasResources = true },
                new Package() { Id = Guid.Parse("71A2BD47-E885-49C7-8A58-7EF4BD936F41"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Permisjon", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til permisjon. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Personale").Id, HasResources = true },
                new Package() { Id = Guid.Parse("91CF61AE-69AB-49D5-B51A-80591C91F255"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Ordinær post til virksomheten", Description = "Denne fullmakten gir tilgang til all mottatt post som ikke innholder sensitiv/taushetsbelagt informasjon som sendes virksomheten. Fullmakten gis normalt til de i virksomheten som håndterer mottak av post. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Post og arkiv").Id, HasResources = true },
                new Package() { Id = Guid.Parse("BB0569A6-2268-49B5-9D38-8158B26124C3"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Post til virksomheten med taushetsbelagt innhold", Description = "Denne fullmakten gir tilgang til all mottatt post som innholder sensitiv/taushetsbelagt informasjon som sendes virksomheten. Fullmakten gis normalt til de i virksomheten som håndterer mottak av post som har taushetsbelagt innhold. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Post og arkiv").Id, HasResources = true },
                new Package() { Id = Guid.Parse("1DBA50D6-F604-48E9-BD41-82321B13E85C"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Skatt næring", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til skatt for næringer. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("4C859601-9B2B-4662-AF39-846F4117AD7A"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Skattegrunnlag", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til innhenting av skattegrunnlag. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("9A61B136-7810-4939-AB6D-84938E9A12C6"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Merverdiavgift", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til merverdiavgift. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("4F4D4567-2384-49FA-B34B-84B4B77139D8"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Motorvognavgifter", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til motorvognavgifter. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("B4E69B54-895E-42C5-BF0D-861A571CD282"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Regnskap og økonomirapportering", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til regnskap og øknomirapportering som ikke tilhører skatt og merverdiavgift. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("A02FC602-872A-4671-B338-8B86A64B534A"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Krav, betalinger og utlegg", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til krav og utlegg. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("1886712B-E077-445A-AB3F-8C8BDEBCCC67"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Revisorattesterer", Description = "Denne fullmakten gir tilgang til alle tjenester som krever revisorattestering. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("74C1DCF6-A760-4065-83F0-8EDC6DEC5DBA"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Særavgifter", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til særavgifter. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("EB9006A6-DBD5-4155-9174-91E182A56715"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Kreditt- og oppgjørsordninger", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til kreditt- og oppgjørsordninger. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("DEB7F8AE-8427-469D-B824-937C146C0489"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Toll", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til toll og fortolling. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Skatt, avgift, regnskap og toll").Id, HasResources = true },
                new Package() { Id = Guid.Parse("36C245DB-3207-449E-92B1-94CB0A0F3031"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Veitransport", Description = "Denne fullmakten gir tilgang til tjenester knyttet til person- og godstransport langs veinettet. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Transport og lagring").Id, HasResources = true },
                new Package() { Id = Guid.Parse("9CC8B401-B4CB-473D-A3FA-96171AEB1389"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Transport i rør", Description = "Denne fullmakten gir tilgang til tjenester knyttet til transport i rør. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Transport og lagring").Id, HasResources = true },
                new Package() { Id = Guid.Parse("9603DD83-BE41-4190-B0A7-97490F4A601D"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Sjøfart", Description = "Denne fullmakten gir tilgang til tjenester knyttet til skipsarbeidstakere og fartøy til sjøs. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Transport og lagring").Id, HasResources = true },
                new Package() { Id = Guid.Parse("3B3BC323-207B-4D56-A21F-97B6875CCC28"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Lufttransport", Description = "Denne fullmakten gir tilgang til tjenester knyttet til luftfartøy og romfartøy. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Transport og lagring").Id, HasResources = true },
                new Package() { Id = Guid.Parse("DFCD3923-CB66-45F7-9535-999B6C0C496D"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Jernbanetransport", Description = "Denne fullmakten gir tilgang til tjenester knyttet til jernbane, inkludert trikk, T-bane og sporvogn. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Transport og lagring").Id, HasResources = true },
                new Package() { Id = Guid.Parse("86A8FF87-3A3D-4F32-A4EF-99C43494BC6E"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Lagring og andre tjenester tilknyttet transport", Description = "Denne fullmakten gir tilgang til tjenester knyttet til lagring og hjelpetjenester i forbindelse med transport, samt post- og kurervirksomhet. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Transport og lagring").Id, HasResources = true },
                new Package() { Id = Guid.Parse("C46A568E-59BA-4835-8C0F-9A3E7D3D308C"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Klientadministrasjon for regnskapsfører og revisor", Description = "Denne tilgangspakken gir bruker mulighet til å administrere tilgang til tjenester det er naturlig at regnskapsfører eller revisor utfører. Bruker kan administrere tilgang til tjenestene til ansatte hos regnskapsfører eller revisor på vegne av deres kunder.", AreaId = Areas.First(t => t.Name == "Administrere tilganger").Id, HasResources = false },
                new Package() { Id = Guid.Parse("4691C710-E0AD-4152-9783-9D1E787F02D3"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Tilgangsstyring", Description = "Denne tilgangspakken gir bruker mulighet til å gi videre tilganger for virksomheten som man selv innehar.", AreaId = Areas.First(t => t.Name == "Administrere tilganger").Id, HasResources = false },
                new Package() { Id = Guid.Parse("15D0015F-E21D-405A-89C5-A21476BA3DF0"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Hovedadministrator", Description = "Denne tilgangspakken gir bruker mulighet til å administrere alle tilganger for virksomheten.", AreaId = Areas.First(t => t.Name == "Administrere tilganger").Id, HasResources = false },
                new Package() { Id = Guid.Parse("3ABE9842-06A5-483F-B76D-A65DEC152B2D"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Kundeadministrator", Description = "Denne tilgangspakken gir bruker mulighet til å administrere tilganger man har mottatt for sine kunder til ansatte i egen virksomheten.", AreaId = Areas.First(t => t.Name == "Administrere tilganger").Id, HasResources = false },
                new Package() { Id = Guid.Parse("A736C33B-C15A-43AC-85BE-A684630E1E59"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Post og telekommunikasjon", Description = "Denne fullmakten gir tilgang til tjenester knyttet til post og telekommunikasjon. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Andre tjenesteytende næringer").Id, HasResources = true },
                new Package() { Id = Guid.Parse("413D79FB-A419-4E74-98F7-AA91389DEB81"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Informasjon og kommunikasjon", Description = "Denne fullmakten gir tilgang til tjenester knyttet til informasjon og kommunikasjon. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Andre tjenesteytende næringer").Id, HasResources = true },
                new Package() { Id = Guid.Parse("8F977B5F-A2F9-4712-88E2-AB1A51A6B26F"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Finansiering og forsikring", Description = "Denne fullmakten gir tilgang til tjenester knyttet til finansiering og forsikring. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Andre tjenesteytende næringer").Id, HasResources = true },
                new Package() { Id = Guid.Parse("A8B18888-2216-4EAA-972D-AE96DA04B1AC"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Annen tjenesteyting", Description = "Denne fullmakten gir tilgang til tjenester knyttet til annen tjenesteyting som f eks organisasjoner og foreninger, reparasjon av datamaskiner og varer til personlig bruk og husholdningsbruk og en rekke personlige tjenester som ikke er nevnt annet sted. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Andre tjenesteytende næringer").Id, HasResources = true },
                new Package() { Id = Guid.Parse("1E40697B-E178-4920-8FBD-AF5164B4D147"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Byggesøknad", Description = "Denne tilgangspakken gir fullmakter til tjenester som ansvarlig søker/tiltakshaver trenger, for eksempel byggesøknader, direkte signerte erklæringer, nabovarsel og eiendomssak. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Bygg, anlegg og eiendom").Id, HasResources = true },
                new Package() { Id = Guid.Parse("482EEE1E-EC79-45BB-8BD0-AF8459CBB9F0"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Plansak", Description = "Denne tilgangspakken gir fullmakter til tjenester som forslagsstiller/ plankonsulent trenger, for eksempel varsel om planopppstart og høring og offentlig ettersyn. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Bygg, anlegg og eiendom").Id, HasResources = true },
                new Package() { Id = Guid.Parse("1E1E8BF9-096F-4DE2-9DB7-B176DB55DB09"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Motta nabo- og planvarsel", Description = "Denne tilgangspakken gir fullmakter til tjenester til å lese og svare på varsel om plan-/byggesak. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Bygg, anlegg og eiendom").Id, HasResources = true },
                new Package() { Id = Guid.Parse("AC655A2F-BE29-4888-9A6C-B21E524FA90E"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Oppføring av bygg og anlegg", Description = "Denne tilgangspakken gir fullmakter til tjenester relatert til oppføring av bygninger og annlegg unntatt plan og byggesaksbehandling. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Bygg, anlegg og eiendom").Id, HasResources = true },
                new Package() { Id = Guid.Parse("B98EC05D-1AC5-4CED-8250-B6D75B83502B"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Kjøp og salg av eiendom", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til kjøp og salg av eiendom. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Bygg, anlegg og eiendom").Id, HasResources = true },
                new Package() { Id = Guid.Parse("565A3110-3D51-4E72-AE4C-B89308E5C96E"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Utleie av eiendom", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til utleie av eiendom. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Bygg, anlegg og eiendom").Id, HasResources = true },
                new Package() { Id = Guid.Parse("79329C4A-D856-4491-965E-BCC4ED5A7453"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Eiendomsmegler", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til omsetning og drift av fast eiendom på oppdrag, som eiendomsmegling og eiendomsforvaltning. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Bygg, anlegg og eiendom").Id, HasResources = true },
                new Package() { Id = Guid.Parse("F56BDB15-686B-46F8-9343-BDE5D7C17648"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Elektrisitet - produsere, overføre og distribuere", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til elektrisitet: produsere, overføre og distribuere. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Energi, vann,avløp og avfall").Id, HasResources = true },
                new Package() { Id = Guid.Parse("27AFE398-B25B-4287-B0FA-C1D03D6C9FA9"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Damp- og varmtvann", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til damp- og varmtvann. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Energi, vann,avløp og avfall").Id, HasResources = true },
                new Package() { Id = Guid.Parse("E7CDA008-F265-4452-B03C-C21B8B51DFE1"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Vann - ta ut fra kilde, rense og distribuere", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til vann: ta ut fra kilde, rense og distribuere. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Energi, vann,avløp og avfall").Id, HasResources = true },
                new Package() { Id = Guid.Parse("FEF4AAC0-D227-4EF6-834B-CC2EB4B942ED"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Samle opp og behandle avløpsvann", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til samle opp og behandle avløpsvann. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Energi, vann,avløp og avfall").Id, HasResources = true },
                new Package() { Id = Guid.Parse("6DCFFDDE-CC5C-4B57-A5A2-CC5AE6AD44FC"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Avfall - samle inn, behandle, bruke og gjenvinne", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til avfall: samle inn, behandle bruke og gjenvinne. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Energi, vann,avløp og avfall").Id, HasResources = true },
                new Package() { Id = Guid.Parse("AB656CF2-1E65-4B5A-A1E3-CD5BD4CB804C"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Miljørydding - rensing og lignende virksomhet", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til miljøryddng, -rensing og lignende virksomhet. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Energi, vann,avløp og avfall").Id, HasResources = true },
                new Package() { Id = Guid.Parse("452BD15D-2CD2-4279-9470-CD97BA8EF1C7"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Utvinning av råolje, naturgass og kull", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til utvinning av råolje, naturgass og kull. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.  ", AreaId = Areas.First(t => t.Name == "Energi, vann,avløp og avfall").Id, HasResources = true },
                new Package() { Id = Guid.Parse("06C13400-8683-4985-9802-CEF13E247F24"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Generelle helfotjenester", Description = "Denne fullmakten gir tilgang til ordinære tjenester knyttet til virksomhetens dialog med Helfo der bruker kan få tilgang til personopplysninger om personer det rapporteres om. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("2EE6E972-2423-4F3A-BD3C-D4871FCC9876"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Helfotjenester med personopplysninger av særlig kategori", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til virksomhetens dialog med Helfo der bruker kan få tilgang til personopplysninger av særlig kategori. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("956CFCF0-AB4C-44D8-98A2-D68C4D59321B"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Starte, endre og avvikle virksomhet", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til å starte, endre og avvikle en virksomhet. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("7DFC669B-70E4-4974-9E11-D6DCA4803AAA"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Aksjer og eierforhold", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til aksjer og eierforhold. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("4717E6E0-1EC2-4354-B825-D9A9E2588FB1"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Attester", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til attestering av virksomhet. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("DF13707E-5252-496A-BC00-DAFFEED1E4B2"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Dokumentbasert tilsyn", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til dokumentbaserte tilsyn. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("75978EFE-2437-421E-8C77-DD61925C7BA4"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Infrastruktur", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til virksomhetens infrastruktur. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("250568E6-ED9F-4BDC-B9E3-DF08BE7181BA"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Patent, varemerke og design", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til patent, varemerke og design. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("D3BA7BBA-195B-4B69-AE68-DF20ECD57097"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Tilskudd, støtte og erstatning", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til å søke tilskudd, støtte og erstatning. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("600BF1BE-61F6-423C-9A13-DF93EE3214A5"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Mine sider hos kommunen", Description = "Denne fullmakten gir generell tilgang til tjenester av typen “mine side” tjenester hos kommuner. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("3050EE51-B60E-48CC-A247-E11E459F00F9"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Politi og domstol", Description = "Denne tilgangspakken gir fullmakter til tjenester knyttet til virksomhetens dialog om juridiske forhold med politi og jusitsmyndigheter. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("AC54A5CA-16D2-4132-AE0D-E5AA8BD1FF6E"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Rapportering av statistikk", Description = "Denne fullmakten gir tilgang til alle pålagte rapportering av statistikk. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("594A2C4B-47A1-48C6-A01C-ED44EC4C05A4"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Forskning", Description = "Denne fullmakten gir tilgang til tjenester knyttet til forskning. Ved regelverksendringer eller innføring av nye digitale tjenester kan det bli endringer i tilganger som fullmakten gir.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("C0EB20C1-2268-48F5-88C5-F26CB47A6B1F"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Eksplisitt tjenestedelegering", Description = "Denne fullmakten er ikke delegerbar, og er ikke knyttet til noen roller i ENhetsregisteret. Tilgang til tjenester knyttet til denne pakken kan gis av Hovedadministrator gjennom enkeltrettighetsdelegering.", AreaId = Areas.First(t => t.Name == "Forhold ved virksomheten").Id, HasResources = true },
                new Package() { Id = Guid.Parse("A784A0B3-2CA1-46C1-97DC-F5DF0DD1AB53"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Konkursbo tilgangsstyring", Description = "Denne fullmakten gir rettighet til å administrere konkursbo. Fullmakten er en engangsdelegering, og den gir ikke tilgang til noen tjenester.  ", AreaId = Areas.First(t => t.Name == "Fullmakter for konkursbo").Id, HasResources = true },
                new Package() { Id = Guid.Parse("5EF836C7-69CC-4EA8-84D6-FB933CC4FC5C"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Konkursbo lesetilgang", Description = "Denne fullmakten delegeres til kreditorer og andre som skal ha lesetilgang til det enkelte konkursbo.  ", AreaId = Areas.First(t => t.Name == "Fullmakter for konkursbo").Id, HasResources = true },
                new Package() { Id = Guid.Parse("0E219609-02C6-44E6-9C80-FE2C1997940E"), ProviderId = digdirProvider.Id, EntityTypeId = entityType.Id, IsDelegable = true, Name = "Konkursbo skrivetilgang", Description = "Denne fullmakten gir bostyrers medhjelper tilgang til å jobbe på vegne av bostyrer. Bostyrer delegerer denne fullmakten sammen med Konkursbo lesetilgang til medhjelper for hvert konkursbo.  ", AreaId = Areas.First(t => t.Name == "Fullmakter for konkursbo").Id, HasResources = true },
            };
        }

        public IEnumerable<AreaGroup> GetGroups()
        {
            return Groups;
        }

        public IEnumerable<Area> GetAreas(Guid groupId)
        {
            return Areas.Where(t => t.GroupId == groupId);
        }
       
        public Area? GetArea(Guid id)
        {
            return Areas.FirstOrDefault(t => t.Id == id);
        }

        public IEnumerable<Package> GetPackages(Guid areaId)
        {
            return Packages.Where(t => t.AreaId == areaId);
        }

        public Package? GetPackage(Guid id)
        {
            return Packages.FirstOrDefault(t => t.Id == id);
        }

        public ExtPackage GetExtPackage(Guid id)
        {
            var package = Packages.First(t => t.Id == id);
            var e = package as ExtPackage;
            e.Area = Areas.First(t => t.Id == package.AreaId);
            return e;
        }


        public IEnumerable<Package> GetAllPackages()
        {
            return Packages;
        }
    }
}
