apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-management
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: access-management
  template:
    spec:
      containers:
        - name: access-management
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: test
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"
