using Altinn.Authorization.Api.Contracts.AccessManagement.ActivityLog;
using Altinn.Authorization.Api.Contracts.AccessManagement.Request;

namespace Altinn.AccessMgmt.PersistenceEF.Models;

/// <summary>
/// One entry in the activity log over assignments, delegations and requests.
/// </summary>
/// <remarks>
/// Rows are written exclusively by database triggers on the assignment, delegation and
/// request tables (see <c>ActivityLogTriggerScripts</c>); the application only reads them.
/// Party, role, package and resource names are denormalized snapshots taken when the event
/// happened, so entries stay renderable after the referenced rows are hard-deleted.
/// The table is range-partitioned on <see cref="When"/>.
/// </remarks>
public class ActivityLog
{
    /// <summary>
    /// Unique identifier for the entry. A version 7 UUID generated by the database.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The main category of the record the entry describes.
    /// </summary>
    public ActivityLogType Type { get; set; }

    /// <summary>
    /// The child record category, or <see langword="null"/> when the entry describes the main record itself.
    /// </summary>
    public ActivityLogSubtype? Subtype { get; set; }

    /// <summary>
    /// The database operation that produced the entry.
    /// </summary>
    public ActivityLogTrigger Trigger { get; set; }

    /// <summary>
    /// The (new) request status for request entries, otherwise <see langword="null"/>.
    /// </summary>
    public RequestStatus? Status { get; set; }

    /// <summary>
    /// When the event happened. For created entries this is the audit valid-from of the row
    /// (which imports may backdate); for updated and deleted entries it is the transaction time.
    /// </summary>
    public DateTimeOffset When { get; set; }

    /// <summary>
    /// The entity that performed the change (audit changed-by).
    /// </summary>
    public Guid? ById { get; set; }

    /// <summary>
    /// Name snapshot of the entity that performed the change.
    /// </summary>
    public string? ByName { get; set; }

    /// <summary>
    /// The system/channel the change came through (audit changed-by-system).
    /// </summary>
    public Guid? SourceId { get; set; }

    /// <summary>
    /// The change operation identifier (trace id) shared by all rows written by one operation.
    /// </summary>
    public string? OperationId { get; set; }

    /// <summary>
    /// The party the access relation is from.
    /// </summary>
    public Guid? FromId { get; set; }

    /// <summary>
    /// Name snapshot of the from-party.
    /// </summary>
    public string? FromName { get; set; }

    /// <summary>
    /// Entity type name snapshot of the from-party.
    /// </summary>
    public string? FromType { get; set; }

    /// <summary>
    /// The party the access relation is to.
    /// </summary>
    public Guid? ToId { get; set; }

    /// <summary>
    /// Name snapshot of the to-party.
    /// </summary>
    public string? ToName { get; set; }

    /// <summary>
    /// Entity type name snapshot of the to-party.
    /// </summary>
    public string? ToType { get; set; }

    /// <summary>
    /// The facilitator party for delegation entries, otherwise <see langword="null"/>.
    /// </summary>
    public Guid? ViaId { get; set; }

    /// <summary>
    /// Name snapshot of the facilitator party.
    /// </summary>
    public string? ViaName { get; set; }

    /// <summary>
    /// Entity type name snapshot of the facilitator party.
    /// </summary>
    public string? ViaType { get; set; }

    /// <summary>
    /// The role held towards the from-party.
    /// </summary>
    public Guid? RoleId { get; set; }

    /// <summary>
    /// Name snapshot of the role.
    /// </summary>
    public string? RoleName { get; set; }

    /// <summary>
    /// The agent role on the to-side of a delegation, otherwise <see langword="null"/>.
    /// </summary>
    public Guid? ViaRoleId { get; set; }

    /// <summary>
    /// Name snapshot of the agent role.
    /// </summary>
    public string? ViaRoleName { get; set; }

    /// <summary>
    /// The access package the entry concerns, when the subtype is Package.
    /// </summary>
    public Guid? PackageId { get; set; }

    /// <summary>
    /// Name snapshot of the access package.
    /// </summary>
    public string? PackageName { get; set; }

    /// <summary>
    /// The resource the entry concerns, when the subtype is Resource or Instance.
    /// </summary>
    public Guid? ResourceId { get; set; }

    /// <summary>
    /// Name snapshot of the resource.
    /// </summary>
    public string? ResourceName { get; set; }

    /// <summary>
    /// The instance URN the entry concerns, when the subtype is Instance.
    /// </summary>
    public string? InstanceId { get; set; }

    /// <summary>
    /// Identifier of the affected row (e.g. AssignmentPackage.Id).
    /// </summary>
    public Guid ItemId { get; set; }

    /// <summary>
    /// Identifier of the affected row's main record (e.g. AssignmentPackage.AssignmentId),
    /// or <see langword="null"/> when the entry describes a main record.
    /// </summary>
    public Guid? ParentId { get; set; }

    /// <summary>
    /// Additional event data as JSON (previous status, request action, provenance references etc.).
    /// </summary>
    public string? Details { get; set; }
}
