name: "CD: Apps"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  find-verticals:
    uses: ./.github/workflows/_find-verticals.yml
    with:
      type: app

  deploy:
    name: Deploy
    needs: find-verticals

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find-verticals.outputs.matrix) }}

    uses: ./.github/workflows/_deploy-app.yml
    with:
      path: ${{ matrix.path }}
      name: ${{ matrix.name }}
      terraform: ${{ matrix.terraform == 'true' }}
      terraformStateFile: ${{ matrix.terraformStateFile }}
