name: "CI: Infra"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  hub:
    name: Hub
    secrets: inherit
    uses: ./.github/workflows/_ci-infra-template.yml
    with:
      environment: prod
      tf_state: hub.tfstate
      working_dir: infra/deploy/hub
