name: "CI: Infra"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  hub:
    name: Hub
    secrets: inherit
    uses: ./.github/workflows/_ci-infra-template.yml
    with:
      environment: prod
      tf_state: hub.tfstate
      working_dir: infra/deploy/hub

  test-spoke:
    name: Test
    secrets: inherit
    uses: ./.github/workflows/_ci-infra-template.yml
    strategy:
      fail-fast: false
      matrix:
        environment: [at21, at22, at23, at24, yt01]
    with:
      environment: ${{ matrix.environment }}
      tf_state: spokes.tfstate
      working_dir: infra/deploy/spoke

  test-register:
    name: Register Test
    secrets: inherit
    uses: ./.github/workflows/_ci-infra-template.yml
    strategy:
      fail-fast: false
      matrix:
        environment: [at21, at22, at23, at24, yt01]
    with:
      environment: ${{ matrix.environment }}
      tf_state: register.tfstate
      working_dir: infra/deploy/altinn-register

  staging-spoke:
    name: Staging
    secrets: inherit
    uses: ./.github/workflows/_ci-infra-template.yml
    strategy:
      fail-fast: false
      matrix:
        environment: [tt02]
    with:
      environment: ${{ matrix.environment }}
      tf_state: spokes.tfstate
      working_dir: infra/deploy/spoke

  staging-register:
    name: Register Staging
    secrets: inherit
    uses: ./.github/workflows/_ci-infra-template.yml
    strategy:
      fail-fast: false
      matrix:
        environment: [tt02]
    with:
      environment: ${{ matrix.environment }}
      tf_state: register.tfstate
      working_dir: infra/deploy/altinn-register

  staging-prod:
    name: Prod
    secrets: inherit
    uses: ./.github/workflows/_ci-infra-template.yml
    strategy:
      fail-fast: false
      matrix:
        environment: [prod]
    with:
      environment: ${{ matrix.environment }}
      tf_state: spokes.tfstate
      working_dir: infra/deploy/spoke

  prod-register:
    name: Register Prod
    secrets: inherit
    uses: ./.github/workflows/_ci-infra-template.yml
    strategy:
      fail-fast: false
      matrix:
        environment: [prod]
    with:
      environment: ${{ matrix.environment }}
      tf_state: register.tfstate
      working_dir: infra/deploy/altinn-register
