name: "DEBUG"

on:
  push:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved dnsutils

      - name: Dump OpenVPN Config
        run: |
          cat << EOF > .github/openvpn.config
          ${{ secrets.OVPN_CONFIG }}
          EOF

      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v3.1.0
        with:
          echo_config: false
          config_file: .github/openvpn.config

      - name: Update DNS
        run: |
          sudo resolvectl dns tun0 ${{ secrets.OVPN_NAMESERVER }}
          sudo resolvectl flush-caches

      - run: route -n
        continue-on-error: true
      - run: nslookup psqlsrvaltinnauthaccessmgmt001at22.postgres.database.azure.com
        continue-on-error: true
      - run: ping -c 4 psqlsrvaltinnauthaccessmgmt001at22.postgres.database.azure.com
