name: Infra CD

on:
  push:
    branches:
      - main
    paths:
      - infra/**
      - .github/workflows/infra-*

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  cert:
    name: Cert
    secrets: inherit
    uses: ./.github/workflows/infra-cd-template.yml
    strategy:
      matrix:
        environment: [at21, at22, at23, at24]
    with:
      environment: ${{ matrix.environment }}
      tf_state: cert.tfstate
      working_dir: infra/deploy/cert

  auth:
    name: Auth
    secrets: inherit
    uses: ./.github/workflows/infra-cd-template.yml
    strategy:
      matrix:
        environment: [at21, at22, at23, at24]
    with:
      environment: ${{ matrix.environment }}
      tf_state: auth.tfstate
      working_dir: infra/deploy/auth
