name: Libs CI

on:
  push:
    branches-ignore:
      - main
    paths:
      - src/**
      - .github/workflows/libs-*

env:
  DOTNET_VERSION: 8.0.x
  DIR: src/libs

jobs:
  bundle:
    name: Bundle Libs
    uses: ./.github/workflows/bundle-template.yml
    with:
      dir: libs

  ci:
    name: CI
    runs-on: ubuntu-latest
    needs: bundle
    strategy:
      matrix:
        name: ${{ fromJson(needs.bundle.outputs.dirs) }}

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        working-directory: ${{ env.DIR }}/${{ matrix.name }}
        run: dotnet build

      - name: Test
        if: always()
        working-directory: ${{ env.DIR }}/${{ matrix.name }}
        run: dotnet test --no-build
