name: mirror-images

on:
  schedule:
    - cron: '0 3 * * SUN'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       user/app:latest
      #       user/app:1.0.0

      - name: Mirror image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/altinn/library/postgres:16.2-alpine \
            docker.io/postgres:16.2-alpine
