name: "PR: Libs"

on:
  push:
    branches-ignore:
      - main
    paths:
      - src/**
      - .github/workflows/libs-*

env:
  DOTNET_VERSION: 8.0.x
  DIR: src/libs

jobs:
  find-verticals:
    uses: ./.github/workflows/_find-verticals.yml
    with:
      type: lib

  ci:
    name: CI
    runs-on: ubuntu-latest
    needs: find-verticals
    strategy:
      matrix: ${{ fromJson(needs.find-verticals.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        working-directory: ${{ matrix.path }}
        run: dotnet build

      - name: Test
        if: always()
        working-directory: ${{ matrix.path }}
        run: dotnet test --no-build
